baseURL = 'https://ssuwat.com'
defaultContentLanguage = 'ko'

[languages]
  [languages.ko]
    languageCode = 'ko-kr'
    title = 'SSUWAT - 맞춤형 웹 솔루션'
    weight = 1
    [languages.ko.params]
      description = "SSUWAT은 웹 페이지, 이커머스, 커뮤니티, 관리자 콘솔 등 맞춤형 웹 솔루션을 제공합니다."
      keywords = "웹개발, 외주, 이커머스, 관리자콘솔, 커뮤니티사이트"
  
  [languages.en]
    languageCode = 'en-us'
    title = 'SSUWAT - Custom Web Solutions'
    weight = 2
    [languages.en.params]
      description = "SSUWAT provides custom web solutions including web pages, e-commerce platforms, community sites, and admin consoles."
      keywords = "web development, outsourcing, ecommerce, admin console, community site"

[params]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true